# Site settings
title: Gái Xinh Chọn Lọc
description: Ngắm gái xinh mỗi ngày.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gaixinhchonloc.github.io" # the base hostname & protocol for your site
author: BOT

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://facebook.com/dinhhiep3107
github_url:
gitlab_url: https://gitlab.com/u/
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://google.com

# Build settings
markdown: kramdown
